'use client';

import { useState, useEffect } from 'react';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

interface Scenario {
  id: string;
  name: string;
  description: string;
  demand_multiplier: number;
  duration_days: number;
  affected_categories: string[];
  probability: number;
  strategies: string[];
  priority_level: string;
}

interface ScenarioResult {
  name: string;
  records_tested: number;
  stockout_count: number;
  stockout_rate: number;
  avg_risk_score: number;
  probability: number;
  strategies: string[];
}

export default function AIScenarioTester() {
  const [scenarios, setScenarios] = useState<Scenario[]>([]);
  const [selectedScenarios, setSelectedScenarios] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<any>(null);
  const [error, setError] = useState<string>('');
  const [useAI, setUseAI] = useState(false);
  const [loadingAI, setLoadingAI] = useState(false);

  // Load available scenarios
  useEffect(() => {
    fetchScenarios(false);
  }, []);

  const fetchScenarios = async (aiMode: boolean) => {
    setLoadingAI(true);
    setUseAI(aiMode);
    try {
      const res = await fetch(`${API_BASE}/adversarial/scenarios?use_ai=${aiMode}`);
      if (res.ok) {
        const data = await res.json();
        setScenarios(data);
        // Default: select top 3 most probable scenarios
        const topScenarios = data
          .sort((a: Scenario, b: Scenario) => b.probability - a.probability)
          .slice(0, 3)
          .map((s: Scenario) => s.id);
        setSelectedScenarios(topScenarios);
      }
    } catch (err) {
      setError('Failed to load scenarios');
    } finally {
      setLoadingAI(false);
    }
  };

  const toggleScenario = (scenarioId: string) => {
    setSelectedScenarios((prev) =>
      prev.includes(scenarioId)
        ? prev.filter((id) => id !== scenarioId)
        : [...prev, scenarioId]
    );
  };

  const runAITest = async () => {
    setLoading(true);
    setError('');
    setResults(null);

    try {
      const res = await fetch(`${API_BASE}/adversarial/run-ai-test`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          scenario_ids: selectedScenarios.length > 0 ? selectedScenarios : null,
        }),
      });

      if (res.ok) {
        const data = await res.json();
        setResults(data);
      } else {
        const errData = await res.json();
        setError(errData.detail || 'Test failed');
      }
    } catch (err) {
      setError('Failed to run AI test');
    } finally {
      setLoading(false);
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical':
        return 'text-red-600 bg-red-50';
      case 'high':
        return 'text-orange-600 bg-orange-50';
      case 'medium':
        return 'text-yellow-600 bg-yellow-50';
      default:
        return 'text-blue-600 bg-blue-50';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">🤖 AI Adversarial Scenario Tester</h1>
          <p className="text-gray-600 mt-1">
            Intelligent stress testing with realistic scenarios and strategic recommendations
          </p>
        </div>
        <div className="flex gap-3">
          <Button
            onClick={() => fetchScenarios(!useAI)}
            disabled={loadingAI}
            className="bg-purple-600 hover:bg-purple-700"
          >
            {loadingAI ? '🔄 Analyzing...' : useAI ? '📚 Use Standard Scenarios' : '🤖 Use AI-Generated Scenarios'}
          </Button>
          <Button
            onClick={runAITest}
            disabled={loading || selectedScenarios.length === 0}
            className="bg-blue-600 hover:bg-blue-700"
          >
            {loading ? '🔄 Running Tests...' : `🚀 Run ${selectedScenarios.length} Scenarios`}
          </Button>
        </div>
      </div>

      {useAI && (
        <Card className="bg-purple-50 border-purple-200">
          <p className="text-sm text-purple-800">
            🤖 <strong>AI Mode Active:</strong> Scenarios generated by Qwen based on YOUR actual database patterns (last 30 days demand, volatility, inventory levels)
          </p>
        </Card>
      )}

      {error && (
        <Card className="bg-red-50 border-red-200">
          <p className="text-red-700">❌ {error}</p>
        </Card>
      )}

      {/* Scenario Selection */}
      <Card>
        <h2 className="text-lg font-semibold mb-4">📋 Select Scenarios to Test</h2>
        <p className="text-sm text-gray-600 mb-4">
          Choose which scenarios to simulate. Each scenario represents a different business risk.
        </p>

        <div className="space-y-3">
          {scenarios.map((scenario) => (
            <div
              key={scenario.id}
              className={`border rounded-lg p-4 cursor-pointer transition-all ${
                selectedScenarios.includes(scenario.id)
                  ? 'border-blue-500 bg-blue-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
              onClick={() => toggleScenario(scenario.id)}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <input
                      type="checkbox"
                      checked={selectedScenarios.includes(scenario.id)}
                      onChange={() => {}}
                      className="w-4 h-4"
                    />
                    <h3 className="font-semibold">{scenario.name}</h3>
                    <span
                      className={`text-xs px-2 py-1 rounded ${getPriorityColor(
                        scenario.priority_level
                      )}`}
                    >
                      {scenario.priority_level.toUpperCase()}
                    </span>
                    <span className="text-sm text-gray-600">
                      {(scenario.probability * 100).toFixed(0)}% probability
                    </span>
                  </div>

                  <p className="text-sm text-gray-700 mb-2">{scenario.description}</p>

                  <div className="flex gap-4 text-xs text-gray-600 mb-2">
                    <span>📈 {scenario.demand_multiplier}× demand spike</span>
                    <span>⏱️ {scenario.duration_days} days</span>
                    <span>
                      📦 {scenario.affected_categories.join(', ') || 'All categories'}
                    </span>
                  </div>

                  <div className="mt-2">
                    <p className="text-xs font-semibold text-gray-700 mb-1">
                      Recommended Strategies:
                    </p>
                    <ul className="text-xs text-gray-600 space-y-1">
                      {scenario.strategies.slice(0, 2).map((strategy, idx) => (
                        <li key={idx}>• {strategy}</li>
                      ))}
                      {scenario.strategies.length > 2 && (
                        <li className="text-gray-500">
                          + {scenario.strategies.length - 2} more...
                        </li>
                      )}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Results Display */}
      {results && (
        <Card className="bg-green-50 border-green-200">
          <h2 className="text-lg font-semibold mb-4 text-green-800">
            ✅ AI Testing Complete
          </h2>

          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="bg-white p-4 rounded">
              <p className="text-2xl font-bold text-blue-600">
                {results.scenarios_tested}
              </p>
              <p className="text-sm text-gray-600">Scenarios Tested</p>
            </div>
            <div className="bg-white p-4 rounded">
              <p className="text-2xl font-bold text-purple-600">
                {results.total_records}
              </p>
              <p className="text-sm text-gray-600">Risk Assessments</p>
            </div>
            <div className="bg-white p-4 rounded">
              <p className="text-2xl font-bold text-red-600">
                {results.most_critical_scenario?.name || 'N/A'}
              </p>
              <p className="text-sm text-gray-600">Most Critical</p>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold">📊 Results by Scenario:</h3>
            {Object.entries(results.results_by_scenario || {}).map(
              ([scenarioId, result]: [string, any]) => (
                <div key={scenarioId} className="bg-white p-4 rounded border">
                  <h4 className="font-semibold mb-2">{result.name}</h4>
                  <div className="grid grid-cols-4 gap-4 text-sm mb-3">
                    <div>
                      <span className="text-gray-600">Stockout Rate:</span>
                      <p className="font-semibold text-red-600">
                        {(result.stockout_rate * 100).toFixed(1)}%
                      </p>
                    </div>
                    <div>
                      <span className="text-gray-600">Records Tested:</span>
                      <p className="font-semibold">{result.records_tested}</p>
                    </div>
                    <div>
                      <span className="text-gray-600">Avg Risk Score:</span>
                      <p className="font-semibold">{result.avg_risk_score.toFixed(3)}</p>
                    </div>
                    <div>
                      <span className="text-gray-600">Probability:</span>
                      <p className="font-semibold">
                        {(result.probability * 100).toFixed(0)}%
                      </p>
                    </div>
                  </div>

                  <div>
                    <p className="text-xs font-semibold text-gray-700 mb-1">
                      Top Strategies:
                    </p>
                    <ul className="text-xs text-gray-600 space-y-1">
                      {result.strategies.slice(0, 3).map((strategy: string, idx: number) => (
                        <li key={idx}>✓ {strategy}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              )
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
