'use client';

import { useState, useEffect } from 'react';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

interface Scenario {
  id: string;
  name: string;
  description: string;
  demand_multiplier: number;
  duration_days: number;
  affected_categories: string[];
  probability: number;
  strategies: string[];
  priority_level: string;
}

interface ScenarioResult {
  name: string;
  records_tested: number;
  stockout_count: number;
  stockout_rate: number;
  avg_risk_score: number;
  probability: number;
  strategies: string[];
}

export default function AIScenarioTester() {
  const [scenarios, setScenarios] = useState<Scenario[]>([]);
  const [selectedScenarios, setSelectedScenarios] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<any>(null);
  const [error, setError] = useState<string>('');
  const [useAI, setUseAI] = useState(false);
  const [loadingAI, setLoadingAI] = useState(false);

  // Load available scenarios
  useEffect(() => {
    fetchScenarios(false);
  }, []);

  const fetchScenarios = async (aiMode: boolean) => {
    setLoadingAI(true);
    setUseAI(aiMode);
    try {
      const res = await fetch(`${API_BASE}/adversarial/scenarios?use_ai=${aiMode}`);
      if (res.ok) {
        const data = await res.json();
        setScenarios(data);
        // Default: select top 3 most probable scenarios
        const topScenarios = data
          .sort((a: Scenario, b: Scenario) => b.probability - a.probability)
          .slice(0, 3)
          .map((s: Scenario) => s.id);
        setSelectedScenarios(topScenarios);
      }
    } catch (err) {
      setError('Failed to load scenarios');
    } finally {
      setLoadingAI(false);
    }
  };

  const toggleScenario = (scenarioId: string) => {
    setSelectedScenarios((prev) =>
      prev.includes(scenarioId)
        ? prev.filter((id) => id !== scenarioId)
        : [...prev, scenarioId]
    );
  };

  const runAITest = async () => {
    setLoading(true);
    setError('');
    setResults(null);

    try {
      const res = await fetch(`${API_BASE}/adversarial/run-ai-test`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          scenario_ids: selectedScenarios.length > 0 ? selectedScenarios : null,
        }),
      });

      if (res.ok) {
        const data = await res.json();
        setResults(data);
      } else {
        const errData = await res.json();
        setError(errData.detail || 'Test failed');
      }
    } catch (err) {
      setError('Failed to run AI test');
    } finally {
      setLoading(false);
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical':
        return 'text-error bg-error/10 border border-error/20';
      case 'high':
        return 'text-warning bg-warning/10 border border-warning/20';
      case 'medium':
        return 'text-accent bg-accent/10 border border-accent/20';
      default:
        return 'text-info bg-info/10 border border-info/20';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold gradient-text">🤖 AI Adversarial Scenario Tester</h1>
          <p className="text-foreground/60 mt-1">
            Intelligent stress testing with realistic scenarios and strategic recommendations
          </p>
        </div>
        <div className="flex gap-3">
          <Button
            onClick={() => fetchScenarios(!useAI)}
            disabled={loadingAI}
            variant="secondary"
            className="border-purple-500/30 bg-purple-500/10 hover:bg-purple-500/20 text-purple-400"
          >
            {loadingAI ? '🔄 Analyzing...' : useAI ? '📚 Use Standard Scenarios' : '🤖 Use AI-Generated Scenarios'}
          </Button>
          <Button
            onClick={runAITest}
            disabled={loading || selectedScenarios.length === 0}
          >
            {loading ? '🔄 Running Tests...' : `🚀 Run ${selectedScenarios.length} Scenarios`}
          </Button>
        </div>
      </div>

      {useAI && (
        <Card className="bg-purple-500/10 border-purple-500/20">
          <p className="text-sm text-purple-300">
            🤖 <strong>AI Mode Active:</strong> Scenarios generated by AI based on YOUR actual database patterns (last 30 days demand, volatility, inventory levels)
          </p>
        </Card>
      )}

      {error && (
        <Card className="bg-error/10 border-error/20">
          <p className="text-error">❌ {error}</p>
        </Card>
      )}

      {/* Scenario Selection */}
      <Card glass>
        <h2 className="text-lg font-semibold mb-4">📋 Select Scenarios to Test</h2>
        <p className="text-sm text-foreground/60 mb-4">
          Choose which scenarios to simulate. Each scenario represents a different business risk.
        </p>

        <div className="space-y-3">
          {scenarios.map((scenario) => (
            <div
              key={scenario.id}
              className={`border rounded-lg p-4 cursor-pointer transition-all duration-300 relative overflow-hidden ${selectedScenarios.includes(scenario.id)
                ? 'border-primary/50 bg-primary/10 shadow-[0_0_25px_rgba(99,102,241,0.15)] scale-[1.01] z-10'
                : 'border-white/10 hover:border-white/20 bg-white/5 hover:translate-x-1'
                }`}
              onClick={() => toggleScenario(scenario.id)}
            >
              {selectedScenarios.includes(scenario.id) && (
                <div className="absolute left-0 top-0 bottom-0 w-1 bg-primary shadow-[0_0_10px_rgba(99,102,241,0.5)]" />
              )}
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <input
                      type="checkbox"
                      checked={selectedScenarios.includes(scenario.id)}
                      onChange={() => { }}
                      className="w-4 h-4 rounded border-primary/50 text-primary bg-white/5 focus:ring-primary accent-primary cursor-pointer"
                    />
                    <h3 className="font-semibold text-foreground">{scenario.name}</h3>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${getPriorityColor(
                        scenario.priority_level
                      )}`}
                    >
                      {scenario.priority_level.toUpperCase()}
                    </span>
                    <span className="text-sm text-foreground/50">
                      {(scenario.probability * 100).toFixed(0)}% probability
                    </span>
                  </div>

                  <p className="text-sm text-foreground/80 mb-2">{scenario.description}</p>

                  <div className="flex gap-4 text-xs text-foreground/60 mb-2">
                    <span className="flex items-center gap-1">📈 {scenario.demand_multiplier}× demand spike</span>
                    <span className="flex items-center gap-1">⏱️ {scenario.duration_days} days</span>
                    <span className="flex items-center gap-1">
                      📦 {scenario.affected_categories.join(', ') || 'All categories'}
                    </span>
                  </div>

                  <div className="mt-2">
                    <p className="text-xs font-semibold text-foreground/70 mb-1">
                      Recommended Strategies:
                    </p>
                    <ul className="text-xs text-foreground/50 space-y-1">
                      {scenario.strategies.slice(0, 2).map((strategy, idx) => (
                        <li key={idx}>• {strategy}</li>
                      ))}
                      {scenario.strategies.length > 2 && (
                        <li className="text-foreground/30">
                          + {scenario.strategies.length - 2} more...
                        </li>
                      )}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Results Display */}
      {results && (
        <Card glass className="border-success/20">
          <h2 className="text-lg font-semibold mb-4 text-success">
            ✅ AI Testing Complete
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white/5 p-4 rounded border border-white/10">
              <p className="text-2xl font-bold text-info">
                {results.scenarios_tested}
              </p>
              <p className="text-xs text-foreground/60 uppercase tracking-wider mt-1">Scenarios Tested</p>
            </div>
            <div className="bg-white/5 p-4 rounded border border-white/10">
              <p className="text-2xl font-bold text-accent">
                {results.total_records}
              </p>
              <p className="text-xs text-foreground/60 uppercase tracking-wider mt-1">Risk Assessments</p>
            </div>
            <div className="bg-white/5 p-4 rounded border border-white/10">
              <p className="text-lg font-bold text-error truncate">
                {results.most_critical_scenario?.name || 'N/A'}
              </p>
              <p className="text-xs text-foreground/60 uppercase tracking-wider mt-1">Most Critical</p>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold">📊 Results by Scenario:</h3>
            {Object.entries(results.results_by_scenario || {}).map(
              ([scenarioId, result]: [string, any]) => (
                <div key={scenarioId} className="bg-white/5 p-4 rounded border border-white/5">
                  <h4 className="font-semibold mb-2">{result.name}</h4>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm mb-3">
                    <div>
                      <span className="text-foreground/50">Stockout Rate:</span>
                      <p className="font-semibold text-error text-lg">
                        {(result.stockout_rate * 100).toFixed(1)}%
                      </p>
                    </div>
                    <div>
                      <span className="text-foreground/50">Records Tested:</span>
                      <p className="font-semibold text-lg">{result.records_tested}</p>
                    </div>
                    <div>
                      <span className="text-foreground/50">Avg Risk Score:</span>
                      <p className="font-semibold text-lg">{result.avg_risk_score.toFixed(3)}</p>
                    </div>
                    <div>
                      <span className="text-foreground/50">Probability:</span>
                      <p className="font-semibold text-lg text-success">
                        {(result.probability * 100).toFixed(0)}%
                      </p>
                    </div>
                  </div>

                  <div>
                    <p className="text-xs font-semibold text-foreground/70 mb-1">
                      Top Strategies:
                    </p>
                    <ul className="text-xs text-foreground/50 space-y-1">
                      {result.strategies.slice(0, 3).map((strategy: string, idx: number) => (
                        <li key={idx}>✓ {strategy}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              )
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
