"""add rebalancing plan table

Revision ID: 7875da9ba487
Revises: 0a3a3107bb5e
Create Date: 2026-01-07 14:30:56.693251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7875da9ba487'
down_revision: Union[str, Sequence[str], None] = '0a3a3107bb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebalancing_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('from_store', sa.String(), nullable=False),
    sa.Column('to_store', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebalancing_plan_id'), 'rebalancing_plan', ['id'], unique=False)
    op.create_index(op.f('ix_rebalancing_plan_sku'), 'rebalancing_plan', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebalancing_plan_sku'), table_name='rebalancing_plan')
    op.drop_index(op.f('ix_rebalancing_plan_id'), table_name='rebalancing_plan')
    op.drop_table('rebalancing_plan')
    # ### end Alembic commands ###
