"""add adversarial risk table

Revision ID: 9afba5c57f40
Revises: 4a524332f044
Create Date: 2026-01-07 12:27:36.682439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afba5c57f40'
down_revision: Union[str, Sequence[str], None] = '4a524332f044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversarial_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('baseline_demand', sa.Float(), nullable=False),
    sa.Column('worst_case_demand', sa.Float(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('days_of_cover', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('stockout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adversarial_risk_id'), 'adversarial_risk', ['id'], unique=False)
    op.create_index(op.f('ix_adversarial_risk_sku'), 'adversarial_risk', ['sku'], unique=False)
    op.create_index(op.f('ix_adversarial_risk_store_id'), 'adversarial_risk', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adversarial_risk_store_id'), table_name='adversarial_risk')
    op.drop_index(op.f('ix_adversarial_risk_sku'), table_name='adversarial_risk')
    op.drop_index(op.f('ix_adversarial_risk_id'), table_name='adversarial_risk')
    op.drop_table('adversarial_risk')
    # ### end Alembic commands ###
